version: '3.1'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=auth_nest
    volumes:
      - './my_postgres_data:/var/lib/postgresql/data'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  my_postgres_data: